

export{}
declare module '@vue/runtime-core' {

  export interface GlobalComponents{
    DAlert: typeof import('./types/vue-devui')['Alert']
DAutoComplete: typeof import('./types/vue-devui')['AutoComplete']
DAvatar: typeof import('./types/vue-devui')['Avatar']
DBadge: typeof import('./types/vue-devui')['Badge']
DButton: typeof import('./types/vue-devui')['Button']
DButtonGroup: typeof import('./types/vue-devui')['ButtonGroup']
DCard: typeof import('./types/vue-devui')['Card']
DCheckbox: typeof import('./types/vue-devui')['Checkbox']
DCheckboxGroup: typeof import('./types/vue-devui')['CheckboxGroup']
DCheckboxButton: typeof import('./types/vue-devui')['CheckboxButton']
DCollapse: typeof import('./types/vue-devui')['Collapse']
DCollapseItem: typeof import('./types/vue-devui')['CollapseItem']
DCountdown: typeof import('./types/vue-devui')['Countdown']
DDatePickerPro: typeof import('./types/vue-devui')['DatePickerPro']
DDRangeDatePickerPro: typeof import('./types/vue-devui')['DRangeDatePickerPro']
DDrawer: typeof import('./types/vue-devui')['Drawer']
DDropdown: typeof import('./types/vue-devui')['Dropdown']
DDropdownMenu: typeof import('./types/vue-devui')['DropdownMenu']
DEditableSelect: typeof import('./types/vue-devui')['EditableSelect']
DForm: typeof import('./types/vue-devui')['Form']
DFormItem: typeof import('./types/vue-devui')['FormItem']
DFormOperation: typeof import('./types/vue-devui')['FormOperation']
DFullscreen: typeof import('./types/vue-devui')['Fullscreen']
DRow: typeof import('./types/vue-devui')['Row']
DCol: typeof import('./types/vue-devui')['Col']
DIcon: typeof import('./types/vue-devui')['Icon']
DIconGroup: typeof import('./types/vue-devui')['IconGroup']
DInput: typeof import('./types/vue-devui')['Input']
DInputNumber: typeof import('./types/vue-devui')['InputNumber']
DLayout: typeof import('./types/vue-devui')['Layout']
DContent: typeof import('./types/vue-devui')['Content']
DHeader: typeof import('./types/vue-devui')['Header']
DFooter: typeof import('./types/vue-devui')['Footer']
DAside: typeof import('./types/vue-devui')['Aside']
DMention: typeof import('./types/vue-devui')['Mention']
DMenu: typeof import('./types/vue-devui')['Menu']
DMenuItem: typeof import('./types/vue-devui')['MenuItem']
DSubMenu: typeof import('./types/vue-devui')['SubMenu']
DModal: typeof import('./types/vue-devui')['Modal']
DModalHeader: typeof import('./types/vue-devui')['Modal']
DModalBody: typeof import('./types/vue-devui')['Modal']
DModalFooter: typeof import('./types/vue-devui')['Modal']
DNotification: typeof import('./types/vue-devui')['Notification']
DFixedOverlay: typeof import('./types/vue-devui')['FixedOverlay']
DFlexibleOverlay: typeof import('./types/vue-devui')['FlexibleOverlay']
DPagination: typeof import('./types/vue-devui')['Pagination']
DPanel: typeof import('./types/vue-devui')['Panel']
DPanelHeader: typeof import('./types/vue-devui')['PanelHeader']
DPanelBody: typeof import('./types/vue-devui')['PanelBody']
DPanelFooter: typeof import('./types/vue-devui')['PanelFooter']
DPopover: typeof import('./types/vue-devui')['Popover']
DProgress: typeof import('./types/vue-devui')['Progress']
DRadio: typeof import('./types/vue-devui')['Radio']
DRadioGroup: typeof import('./types/vue-devui')['RadioGroup']
DRadioButton: typeof import('./types/vue-devui')['RadioButton']
DRate: typeof import('./types/vue-devui')['Rate']
DResult: typeof import('./types/vue-devui')['Result']
DSearch: typeof import('./types/vue-devui')['Search']
DSelect: typeof import('./types/vue-devui')['Select']
DOption: typeof import('./types/vue-devui')['Option']
DOptionGroup: typeof import('./types/vue-devui')['OptionGroup']
DSkeleton: typeof import('./types/vue-devui')['Skeleton']
DSkeletonItem: typeof import('./types/vue-devui')['SkeletonItem']
DSlider: typeof import('./types/vue-devui')['Slider']
DSplitter: typeof import('./types/vue-devui')['Splitter']
DSplitterPane: typeof import('./types/vue-devui')['SplitterPane']
DStatistic: typeof import('./types/vue-devui')['Statistic']
DStatus: typeof import('./types/vue-devui')['Status']
DSteps: typeof import('./types/vue-devui')['Steps']
DStep: typeof import('./types/vue-devui')['Step']
DSwitch: typeof import('./types/vue-devui')['Switch']
DTable: typeof import('./types/vue-devui')['Table']
DColumn: typeof import('./types/vue-devui')['Column']
DTabs: typeof import('./types/vue-devui')['Tabs']
DTab: typeof import('./types/vue-devui')['Tab']
DTag: typeof import('./types/vue-devui')['Tag']
DTextarea: typeof import('./types/vue-devui')['Textarea']
DTimePicker: typeof import('./types/vue-devui')['TimePicker']
DTimeSelect: typeof import('./types/vue-devui')['TimeSelect']
DTimeline: typeof import('./types/vue-devui')['Timeline']
DTimelineItem: typeof import('./types/vue-devui')['TimelineItem']
DTooltip: typeof import('./types/vue-devui')['Tooltip']
DTree: typeof import('./types/vue-devui')['Tree']
DUpload: typeof import('./types/vue-devui')['Upload']
  }


  export interface ComponentCustomProps {
    vDImagePreview?: typeof import('./types/vue-devui')['ImagePreviewDirective']
vLoading?: typeof import('./types/vue-devui')['LoadingDirective']
vRipple?: typeof import('./types/vue-devui')['RippleDirective']
vfileDrop?: typeof import('./types/vue-devui')['FileDropDirective']
  }


  export interface ComponentCustomProperties{
    $drawerService?: typeof import('./types/vue-devui')['DrawerService']
$imagePreviewService?: typeof import('./types/vue-devui')['ImagePreviewService']
$loadingService?: typeof import('./types/vue-devui')['LoadingService']
$message?: typeof import('./types/vue-devui')['Message']
$notificationService?: typeof import('./types/vue-devui')['NotificationService']
  }


}
