import type { App } from 'vue';
import { Accordion } from './accordion';
import { Alert } from './alert';
import { Anchor } from './anchor';
import { AutoComplete } from './auto-complete';
import { Avatar } from './avatar';
import { BackTop } from './back-top';
import { Badge } from './badge';
import { Breadcrumb } from './breadcrumb';
import { Button, ButtonGroup } from './button';
import { Card } from './card';
import { Carousel, CarouselItem } from './carousel';
import { Cascader } from './cascader';
import { Checkbox, CheckboxGroup, CheckboxButton } from './checkbox';
import { Collapse, CollapseItem } from './collapse';
import { ColorPicker } from './color-picker';
import { Comment } from './comment';
import { Countdown } from './countdown';
import { DatePicker, StickSlider } from './date-picker';
import { DatePickerPro, DRangeDatePickerPro } from './date-picker-pro';
import { DraggableDirective, DroppableDirective, SortableDirective } from './dragdrop';
import { Drawer, DrawerService } from './drawer';
import { Dropdown, DropdownMenu } from './dropdown';
import { EditableSelect } from './editable-select';
import { Form, FormItem, FormOperation } from './form';
import { Fullscreen } from './fullscreen';
import { Gantt } from './gantt';
import { Row, Col } from './grid';
import { Icon, IconGroup } from './icon';
import { ImagePreviewDirective, ImagePreviewService } from './image-preview';
import { Input } from './input';
import { InputIcon } from './input-icon';
import { InputNumber } from './input-number';
import { Layout, Content, Header, Footer, Aside } from './layout';
import { List, ListItem } from './list';
import { LoadingService, LoadingDirective } from './loading';
import { Mention } from './mention';
import { Menu, SubMenu, MenuItem } from './menu';
import { Message } from './message';
import { Modal } from './modal';
import { MultiAutoComplete } from './multi-auto-complete';
import { NavSprite } from './nav-sprite';
import { Notification, NotificationService } from './notification';
import { FlexibleOverlay, FixedOverlay } from './overlay';
import { Pagination } from './pagination';
import { Panel, PanelHeader, PanelBody, PanelFooter } from './panel';
import { Popover } from './popover';
import { Progress } from './progress';
import { QuadrantDiagram } from './quadrant-diagram';
import { Radio, RadioGroup, RadioButton } from './radio';
import { Rate } from './rate';
import { ReadTip } from './read-tip';
import { Result } from './result';
import { RippleDirective } from './ripple';
import { Search } from './search';
import { Select, Option, OptionGroup } from './select';
import { Skeleton, SkeletonItem } from './skeleton';
import { Slider } from './slider';
import { Splitter } from './splitter';
import { Statistic } from './statistic';
import { Status } from './status';
import { Steps, Step } from './steps';
import { StepsGuide, StepsGuideDirective } from './steps-guide';
import { Sticky } from './sticky';
import { Switch } from './switch';
import { Table, Column } from './table';
import { Tabs, Tab } from './tabs';
import { Tag } from './tag';
import { TagInput } from './tag-input';
import { Textarea } from './textarea';
import { TimePicker } from './time-picker';
import { TimeSelect } from './time-select';
import { Timeline, TimelineItem } from './timeline';
import { Tooltip } from './tooltip';
import { Transfer } from './transfer';
import { Tree } from './tree';
import { TreeSelect } from './tree-select';
import { Upload } from './upload';
import { VirtualList } from './virtual-list';
import './style/devui.scss';
export { Accordion, Alert, Anchor, AutoComplete, Avatar, BackTop, Badge, Breadcrumb, Button, ButtonGroup, Card, Carousel, CarouselItem, Cascader, Checkbox, CheckboxGroup, CheckboxButton, Collapse, CollapseItem, ColorPicker, Comment, Countdown, DatePicker, StickSlider, DatePickerPro, DRangeDatePickerPro, DraggableDirective, DroppableDirective, SortableDirective, Drawer, DrawerService, Dropdown, DropdownMenu, EditableSelect, Form, FormItem, FormOperation, Fullscreen, Gantt, Row, Col, Icon, IconGroup, ImagePreviewDirective, ImagePreviewService, Input, InputIcon, InputNumber, Layout, Content, Header, Footer, Aside, List, ListItem, LoadingService, LoadingDirective, Mention, Menu, SubMenu, MenuItem, Message, Modal, MultiAutoComplete, NavSprite, Notification, NotificationService, FlexibleOverlay, FixedOverlay, Pagination, Panel, PanelHeader, PanelBody, PanelFooter, Popover, Progress, QuadrantDiagram, Radio, RadioGroup, RadioButton, Rate, ReadTip, Result, RippleDirective, Search, Select, Option, OptionGroup, Skeleton, SkeletonItem, Slider, Splitter, Statistic, Status, Steps, Step, StepsGuide, StepsGuideDirective, Sticky, Switch, Table, Column, Tabs, Tab, Tag, TagInput, Textarea, TimePicker, TimeSelect, Timeline, TimelineItem, Tooltip, Transfer, Tree, TreeSelect, Upload, VirtualList };
declare const _default: {
    version: string;
    install(app: App): void;
};
export default _default;
